# ANN (Artificial Neural Network)

In [33]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (1.82.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [34]:
import sys
!{sys.executable} -m pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (1.82.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [35]:
!pip install keras

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keras in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (3.15.0)
Requirement already satisfied: absl-py in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras) (2.5.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from keras) (2.3.5)
Requirement already satisfied: rich in c:\programdata\anaconda3\lib\site-packages (from keras) (14.2.0)
Requirement already satisfied: namex in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras) (3.14.0)
Requirement already satisfied: optree in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\mohd ali\appdata\roaming\python\python313\site-packages (from keras) (0.5.4)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from keras) (25.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from optree->keras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [1]:
import tensorflow as tf
from tensorflow import keras

print("TensorFlow Version:", tf.__version__)
print("Keras Version:", keras.__version__)

TensorFlow Version: 2.21.0
Keras Version: 3.15.0

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset=pd.read_csv("credit_card_fraud_dataset.csv")

In [3]:
dataset.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [4]:
dataset.shape

(100000, 7)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   TransactionID    100000 non-null  int64
 1   TransactionDate  100000 non-null  object
 2   Amount           100000 non-null  float64
 3   MerchantID       100000 non-null  int64
 4   TransactionType  100000 non-null  object
 5   Location         100000 non-null  object
 6   IsFraud          100000 non-null  int64
dtypes: float64(1), int64(3), object(3)
memory usage: 5.3+ MB

In [7]:
dataset.isnull().sum()

TransactionID      0
TransactionDate    0
Amount             0
MerchantID         0
TransactionType    0
Location           0
IsFraud            0
dtype: int64

In [8]:
dataset["IsFraud"].value_counts()

IsFraud
0    99000
1     1000
Name: count, dtype: int64

In [10]:
dataset["IsFraud"].value_counts(normalize=True)*100

IsFraud
0    99.0
1     1.0
Name: proportion, dtype: float64

In [12]:
dataset["TransactionDate"] = pd.to_datetime(dataset["TransactionDate"])

In [13]:
dataset["Year"] = dataset["TransactionDate"].dt.year
dataset["Month"] = dataset["TransactionDate"].dt.month
dataset["Day"] = dataset["TransactionDate"].dt.day
dataset["Hour"] = dataset["TransactionDate"].dt.hour

In [14]:
from sklearn.preprocessing import LabelEncoder
le_type = LabelEncoder()
le_location = LabelEncoder()
dataset["TransactionType"]=le_type.fit_transform(dataset["TransactionType"])
dataset["Location"] = le_location.fit_transform(dataset["Location"])

In [15]:
dataset.drop(["TransactionID","TransactionDate"],axis=1,inplace=True)

In [16]:
dataset.head()

,Amount,MerchantID,TransactionType,Location,IsFraud,Year,Month,Day,Hour
0,4189.27,688,1,7,0,2024,4,3,14
1,2659.71,109,1,1,0,2024,3,19,13
2,784.00,394,0,4,0,2024,1,8,10
3,3514.40,944,0,5,0,2024,4,13,23
4,369.07,475,0,6,0,2024,7,12,18

In [18]:
X = dataset.drop("IsFraud", axis=1)
y = dataset["IsFraud"]

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train =scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [23]:
from imblearn.over_sampling import SMOTE
smote =SMOTE(random_state=42)
X_train,y_train=smote.fit_resample(X_train,y_train)
print(X_train.shape)
print(y_train.value_counts())

(158400, 8)
IsFraud
0    79200
1    79200
Name: count, dtype: int64

In [25]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()

model.add(Dense(64, activation="relu", input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))

model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))

model.add(Dense(16, activation="relu"))

model.add(Dense(1, activation="sigmoid"))

In [27]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [28]:
history= model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

Epoch 1/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.6268 - loss: 0.6453 - val_accuracy: 0.1662 - val_loss: 0.8522
Epoch 2/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.6400 - loss: 0.6246 - val_accuracy: 0.3997 - val_loss: 0.7889
Epoch 3/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.6545 - loss: 0.6102 - val_accuracy: 0.5689 - val_loss: 0.7108
Epoch 4/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - accuracy: 0.6649 - loss: 0.5997 - val_accuracy: 0.5368 - val_loss: 0.7266
Epoch 5/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.6723 - loss: 0.5904 - val_accuracy: 0.5911 - val_loss: 0.6976
Epoch 6/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.6777 - loss: 0.5832 - val_accuracy: 0.6075 - val_loss: 0.6801
Epoch 7/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.6831 - loss: 0.5775 - val_accuracy: 0.6367 - val_loss: 0.6674
Epoch 8/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.6894 - loss: 0.5714 - val_accuracy: 0.6764 - val_loss: 0.6351
Epoch 9/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.6912 - loss: 0.5686 - val_accuracy: 0.6890 - val_loss: 0.6283
Epoch 10/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - accuracy: 0.6947 - loss: 0.5641 - val_accuracy: 0.7255 - val_loss: 0.6019
Epoch 11/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.6971 - loss: 0.5615 - val_accuracy: 0.7432 - val_loss: 0.5829
Epoch 12/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - accuracy: 0.7000 - loss: 0.5582 - val_accuracy: 0.7352 - val_loss: 0.5802
Epoch 13/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.7019 - loss: 0.5563 - val_accuracy: 0.7644 - val_loss: 0.5604
Epoch 14/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - accuracy: 0.7037 - loss: 0.5534 - val_accuracy: 0.7332 - val_loss: 0.5905
Epoch 15/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - accuracy: 0.7050 - loss: 0.5518 - val_accuracy: 0.7832 - val_loss: 0.5593
Epoch 16/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.7069 - loss: 0.5517 - val_accuracy: 0.6897 - val_loss: 0.6301
Epoch 17/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - accuracy: 0.7082 - loss: 0.5510 - val_accuracy: 0.7543 - val_loss: 0.5792
Epoch 18/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.7084 - loss: 0.5490 - val_accuracy: 0.7454 - val_loss: 0.5862
Epoch 19/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.7095 - loss: 0.5470 - val_accuracy: 0.7540 - val_loss: 0.5808
Epoch 20/20
3960/3960 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.7105 - loss: 0.5462 - val_accuracy: 0.7867 - val_loss: 0.5405

In [29]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.76      0.86     19800
           1       0.01      0.28      0.02       200

    accuracy                           0.75     20000
   macro avg       0.50      0.52      0.44     20000
weighted avg       0.98      0.75      0.85     20000

In [31]:
import pickle
model.save("fraud_model.keras")

pickle.dump(scaler, open("scaler.pkl", "wb"))

pickle.dump(
    {
        "TransactionType": le_type,
        "Location": le_location
    },
    open("label_encoders.pkl", "wb")
)

print("Model Saved Successfully")

Model Saved Successfully

In [ ]:
*-