In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Sale_Report.csv")
df

      index       SKU Code Design No.  Stock       Category Size Color
0         0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1         1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2         2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3         3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4         4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red
...     ...            ...        ...    ...            ...  ...   ...
9266   9266            NaN        NaN    NaN            NaN  NaN   NaN
9267   9267            NaN        NaN    NaN            NaN  NaN   NaN
9268   9268            NaN        NaN    NaN            NaN  NaN   NaN
9269   9269            NaN        NaN    NaN            NaN  NaN   NaN
9270   9270            NaN        NaN    NaN            NaN  NaN   NaN

[9271 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9271 entries, 0 to 9270
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9271 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9235 non-null   object
 3   Stock       9235 non-null   float64
 4   Category    9226 non-null   object
 5   Size        9235 non-null   object
 6   Color       9226 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 507.1+ KB

In [5]:
df.describe()

             index        Stock
count  9271.000000  9235.000000
mean   4635.000000    26.246454
std    2676.451507    58.462891
min       0.000000     0.000000
25%    2317.500000     3.000000
50%    4635.000000     8.000000
75%    6952.500000    31.000000
max    9270.000000  1234.000000

In [6]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9266    False
9267    False
9268    False
9269    False
9270    False
Length: 9271, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head()

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

In [9]:
df.tail()

      index SKU Code Design No.  Stock Category Size Color
9266   9266      NaN        NaN    NaN      NaN  NaN   NaN
9267   9267      NaN        NaN    NaN      NaN  NaN   NaN
9268   9268      NaN        NaN    NaN      NaN  NaN   NaN
9269   9269      NaN        NaN    NaN      NaN  NaN   NaN
9270   9270      NaN        NaN    NaN      NaN  NaN   NaN

In [10]:
df.isnull()

      index  SKU Code  Design No.  Stock  Category   Size  Color
0     False     False       False  False     False  False  False
1     False     False       False  False     False  False  False
2     False     False       False  False     False  False  False
3     False     False       False  False     False  False  False
4     False     False       False  False     False  False  False
...     ...       ...         ...    ...       ...    ...    ...
9266  False      True        True   True      True   True   True
9267  False      True        True   True      True   True   True
9268  False      True        True   True      True   True   True
9269  False      True        True   True      True   True   True
9270  False      True        True   True      True   True   True

[9271 rows x 7 columns]

In [11]:
df.sample(5)

      index        SKU Code Design No.  Stock   Category Size            Color
5016   5016    JNE3619-KR-S    JNE3619   24.0      KURTA    S            Black
4928   4928  JNE3606-KR-XXL    JNE3606   15.0      KURTA  XXL            Beige
5541   5541   JNE3710-DR-XL    JNE3710    2.0      DRESS   XL             Blue
4816   4816   JNE3570-KR-XS    JNE3570    3.0      KURTA   XS      Light Green
7554   7554  SET094-KR-NP-M     SET094   10.0  KURTA SET    M  Turquoise Green

In [12]:
df.shape

(9271, 7)

In [13]:
df.info

<bound method DataFrame.info of       index       SKU Code Design No.  Stock       Category Size Color
0         0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1         1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2         2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3         3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4         4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red
...     ...            ...        ...    ...            ...  ...   ...
9266   9266            NaN        NaN    NaN            NaN  NaN   NaN
9267   9267            NaN        NaN    NaN            NaN  NaN   NaN
9268   9268            NaN        NaN    NaN            NaN  NaN   NaN
9269   9269            NaN        NaN    NaN            NaN  NaN   NaN
9270   9270            NaN        NaN    NaN            NaN  NaN   NaN

[9271 rows x 7 columns]>

In [14]:
df.memory_usage()

Index           132
index         74168
SKU Code      74168
Design No.    74168
Stock         74168
Category      74168
Size          74168
Color         74168
dtype: int64

In [15]:
len(df)

9271