# Logistic  Regression

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [3]:
df=pd.read_csv("data.csv")

In [4]:
df.head()

   SNo       X_1       X_2   y
0    0 -0.869144  0.389310  0.0
1    1 -0.993467 -0.610591  0.0
2    2 -0.834064  0.239236  0.0
3    3 -0.136471  0.632003  1.0
4    4  0.403887  0.310784  1.0

In [5]:
df.isnull().sum()

SNo    0
X_1    0
X_2    0
y      0
dtype: int64

In [6]:
df.tail()

    SNo       X_1       X_2   y
95   95  0.531635 -0.479185  1.0
96   96 -0.650192  0.655303  1.0
97   97  0.985299  0.118333  1.0
98   98 -0.275289  0.005730  1.0
99   99  0.281860  0.726376  1.0

In [7]:
df.shape

(100, 4)

In [8]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [9]:
x

    SNo       X_1       X_2
0     0 -0.869144  0.389310
1     1 -0.993467 -0.610591
2     2 -0.834064  0.239236
3     3 -0.136471  0.632003
4     4  0.403887  0.310784
..  ...       ...       ...
95   95  0.531635 -0.479185
96   96 -0.650192  0.655303
97   97  0.985299  0.118333
98   98 -0.275289  0.005730
99   99  0.281860  0.726376

[100 rows x 3 columns]

In [10]:
y

0     0.0
1     0.0
2     0.0
3     1.0
4     1.0
     ...
95    1.0
96    1.0
97    1.0
98    1.0
99    1.0
Name: y , Length: 100, dtype: float64

In [11]:
x

    SNo       X_1       X_2
0     0 -0.869144  0.389310
1     1 -0.993467 -0.610591
2     2 -0.834064  0.239236
3     3 -0.136471  0.632003
4     4  0.403887  0.310784
..  ...       ...       ...
95   95  0.531635 -0.479185
96   96 -0.650192  0.655303
97   97  0.985299  0.118333
98   98 -0.275289  0.005730
99   99  0.281860  0.726376

[100 rows x 3 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x , y, test_size = 0.25 , random_state = 42)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:

classifier = LogisticRegression()

In [15]:
classifier.fit(X_train , y_train)

LogisticRegression()

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1.])

In [18]:
y_test

83    1.0
53    0.0
70    0.0
45    0.0
44    0.0
39    0.0
22    0.0
80    1.0
10    0.0
0     0.0
18    1.0
30    1.0
73    1.0
33    1.0
90    1.0
4     1.0
76    1.0
77    1.0
12    1.0
31    1.0
55    0.0
88    1.0
26    1.0
42    1.0
69    1.0
Name: y , dtype: float64

In [19]:
from sklearn.metrics import accuracy_score , classification_report

In [20]:
print(accuracy_score(y_pred,y_test))

0.88

In [21]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

         0.0       0.89      0.80      0.84        10
         1.0       0.88      0.93      0.90        15

    accuracy                           0.88        25
   macro avg       0.88      0.87      0.87        25
weighted avg       0.88      0.88      0.88        25

In [22]:
pickle.dump(classifier, open("model.pkl", "wb"))